{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Login Succeeded\n",
      "Stopping docker: [  OK  ]\n",
      "Starting docker:\t.[  OK  ]\n",
      "Sending build context to Docker daemon  24.58kB\n",
      "Step 1/12 : FROM 763104351884.dkr.ecr.us-east-1.amazonaws.com/tensorflow-training:2.0.0-cpu-py36-ubuntu18.04\n",
      " ---> a709409e7f8c\n",
      "Step 2/12 : RUN apt-get update &&     apt-get install -y nginx\n",
      " ---> Using cache\n",
      " ---> 031ff00c7cd9\n",
      "Step 3/12 : RUN pip install gevent gunicorn flask\n",
      " ---> Using cache\n",
      " ---> fe4bd0c9aa1f\n",
      "Step 4/12 : ENV PATH=\"/opt/program:${PATH}\"\n",
      " ---> Using cache\n",
      " ---> 226cacf9a480\n",
      "Step 5/12 : COPY code /opt/program\n",
      " ---> 0a111ac59797\n",
      "Step 6/12 : WORKDIR /opt/program\n",
      " ---> Running in a3c87d13f2a0\n",
      "Removing intermediate container a3c87d13f2a0\n",
      " ---> 518f35bb47c6\n",
      "Step 7/12 : FROM 763104351884.dkr.ecr.us-east-1.amazonaws.com/tensorflow-training:2.0.0-cpu-py36-ubuntu18.04\n",
      " ---> a709409e7f8c\n",
      "Step 8/12 : RUN apt-get update &&     apt-get install -y nginx\n",
      " ---> Using cache\n",
      " ---> 031ff00c7cd9\n",
      "Step 9/12 : RUN pip install gevent gunicorn flask\n",
      " ---> Using cache\n",
      " ---> fe4bd0c9aa1f\n",
      "Step 10/12 : ENV PATH=\"/opt/program:${PATH}\"\n",
      " ---> Using cache\n",
      " ---> 226cacf9a480\n",
      "Step 11/12 : COPY code /opt/program\n",
      " ---> Using cache\n",
      " ---> 0a111ac59797\n",
      "Step 12/12 : WORKDIR /opt/program\n",
      " ---> Using cache\n",
      " ---> 518f35bb47c6\n",
      "Successfully built 518f35bb47c6\n",
      "Successfully tagged image-classifier:latest\n",
      "The push refers to repository [731833107751.dkr.ecr.us-east-1.amazonaws.com/image-classifier]\n",
      "c4897523d47a: Preparing\n",
      "3c7f185c074d: Preparing\n",
      "332bc7632212: Preparing\n",
      "ff163d2dbaa0: Preparing\n",
      "98409a5049e8: Preparing\n",
      "81ba7e575670: Preparing\n",
      "b659efa16f45: Preparing\n",
      "c5c857481934: Preparing\n",
      "9dfc8f720d4e: Preparing\n",
      "fbecce06f56f: Preparing\n",
      "c80752c5d6fb: Preparing\n",
      "43d03c732171: Preparing\n",
      "f68d7830867c: Preparing\n",
      "3136a32fedc8: Preparing\n",
      "0d4980157bbc: Preparing\n",
      "faafda22c60e: Preparing\n",
      "f994bc2ffc81: Preparing\n",
      "cd417f0f234f: Preparing\n",
      "918efb8f161b: Preparing\n",
      "27dd43ea46a8: Preparing\n",
      "9f3bfcc4a1a8: Preparing\n",
      "2dc9f76fb25b: Preparing\n",
      "f68d7830867c: Waiting\n",
      "3136a32fedc8: Waiting\n",
      "0d4980157bbc: Waiting\n",
      "faafda22c60e: Waiting\n",
      "f994bc2ffc81: Waiting\n",
      "cd417f0f234f: Waiting\n",
      "918efb8f161b: Waiting\n",
      "9f3bfcc4a1a8: Waiting\n",
      "2dc9f76fb25b: Waiting\n",
      "27dd43ea46a8: Waiting\n",
      "c5c857481934: Waiting\n",
      "9dfc8f720d4e: Waiting\n",
      "fbecce06f56f: Waiting\n",
      "c80752c5d6fb: Waiting\n",
      "43d03c732171: Waiting\n",
      "81ba7e575670: Waiting\n",
      "b659efa16f45: Waiting\n",
      "ff163d2dbaa0: Layer already exists\n",
      "98409a5049e8: Layer already exists\n",
      "3c7f185c074d: Layer already exists\n",
      "332bc7632212: Layer already exists\n",
      "81ba7e575670: Layer already exists\n",
      "c5c857481934: Layer already exists\n",
      "b659efa16f45: Layer already exists\n",
      "9dfc8f720d4e: Layer already exists\n",
      "c80752c5d6fb: Layer already exists\n",
      "fbecce06f56f: Layer already exists\n",
      "f68d7830867c: Layer already exists\n",
      "43d03c732171: Layer already exists\n",
      "3136a32fedc8: Layer already exists\n",
      "0d4980157bbc: Layer already exists\n",
      "faafda22c60e: Layer already exists\n",
      "f994bc2ffc81: Layer already exists\n",
      "918efb8f161b: Layer already exists\n",
      "cd417f0f234f: Layer already exists\n",
      "27dd43ea46a8: Layer already exists\n",
      "2dc9f76fb25b: Layer already exists\n",
      "9f3bfcc4a1a8: Layer already exists\n",
      "c4897523d47a: Pushed\n",
      "latest: digest: sha256:c4ae1dd709d413f46cfda6c26385ad3142cf4ea6c744cb57de565a324040115c size: 4921\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING! Using --password via the CLI is insecure. Use --password-stdin.\n",
      "WARNING! Your password will be stored unencrypted in /home/ec2-user/.docker/config.json.\n",
      "Configure a credential helper to remove this warning. See\n",
      "https://docs.docker.com/engine/reference/commandline/login/#credentials-store\n",
      "\n"
     ]
    }
   ],
   "source": [
    "%%sh\n",
    "\n",
    "# The name of our algorithm\n",
    "algorithm_name=image-classifier\n",
    "\n",
    "cd container\n",
    "\n",
    "chmod +x code/train-mnist\n",
    "#chmod +x code/serve\n",
    "\n",
    "account=$(aws sts get-caller-identity --query Account --output text)\n",
    "\n",
    "# Get the region defined in the current configuration (default to us-west-2 if none defined)\n",
    "region=$(aws configure get region)\n",
    "region=${region:-us-east-1}\n",
    "\n",
    "fullname=\"${account}.dkr.ecr.${region}.amazonaws.com/${algorithm_name}:latest\"\n",
    "\n",
    "# If the repository doesn't exist in ECR, create it.\n",
    "\n",
    "aws ecr describe-repositories --repository-names \"${algorithm_name}\" > /dev/null 2>&1\n",
    "\n",
    "if [ $? -ne 0 ]\n",
    "then\n",
    "    aws ecr create-repository --repository-name \"${algorithm_name}\" > /dev/null\n",
    "fi\n",
    "\n",
    "# Get the login command from ECR and execute it directly\n",
    "$(aws ecr get-login --region ${region} --no-include-email)\n",
    "\n",
    "# Build the docker image locally with the image name and then push it to ECR\n",
    "# with the full name.\n",
    "\n",
    "# On a SageMaker Notebook Instance, the docker daemon may need to be restarted in order\n",
    "# to detect your network configuration correctly.  (This is a known issue.)\n",
    "if [ -d \"/home/ec2-user/SageMaker\" ]; then\n",
    "  sudo service docker restart\n",
    "fi\n",
    "\n",
    "docker build  -t ${algorithm_name} .\n",
    "docker tag ${algorithm_name} ${fullname}\n",
    "\n",
    "docker push ${fullname}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "# S3 prefix\n",
    "prefix = 'image-classifier'\n",
    "\n",
    "# Define IAM role\n",
    "import boto3\n",
    "import re\n",
    "\n",
    "import os\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "from sagemaker import get_execution_role\n",
    "\n",
    "role = get_execution_role()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create session\n",
    "import sagemaker as sage\n",
    "from time import gmtime, strftime\n",
    "\n",
    "sess = sage.Session()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "sagemaker-us-east-1-731833107751\n"
     ]
    }
   ],
   "source": [
    "print(sess.default_bucket())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "# upload data for training\n",
    "WORK_DIRECTORY = 'mnist-data' \n",
    " \n",
    "bucket = sess.default_bucket()\n",
    "\n",
    "s3 = boto3.client('s3')\n",
    "s3.download_file(bucket, 'mnist-data/x_train.npy','data/x_train.npy')\n",
    "s3.download_file(bucket, 'mnist-data/y_train.npy','data/y_train.npy')\n",
    "s3.download_file(bucket, 'mnist-data/x_test.npy','data/x_test.npy')\n",
    "s3.download_file(bucket, 'mnist-data/y_test.npy','data/y_test.npy')\n",
    " \n",
    "  "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "s3://sagemaker-us-east-1-731833107751/mnist-data\n",
      "sagemaker-us-east-1-731833107751\n"
     ]
    }
   ],
   "source": [
    "data_location = \"s3://{}/mnist-data\".format(sess.default_bucket()) #\"s3://\" + sess.default_bucket() + \"/mnist-data\"  \n",
    "print(data_location)\n",
    "print(sess.default_bucket())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2020-02-06 22:22:22 Starting - Starting the training job...\n",
      "2020-02-06 22:22:25 Starting - Launching requested ML instances......\n",
      "2020-02-06 22:23:28 Starting - Preparing the instances for training...\n",
      "2020-02-06 22:24:23 Downloading - Downloading input data\n",
      "2020-02-06 22:24:23 Training - Downloading the training image......\n",
      "2020-02-06 22:25:18 Uploading - Uploading generated training model\n",
      "2020-02-06 22:25:18 Failed - Training job failed\n",
      "\u001b[34m2020-02-06 22:25:13,535 sagemaker-containers INFO     Imported framework sagemaker_tensorflow_container.training\u001b[0m\n",
      "\u001b[34m2020-02-06 22:25:13,541 sagemaker-containers INFO     No GPUs detected (normal if no gpus installed)\u001b[0m\n",
      "\u001b[34m2020-02-06 22:25:13,552 sagemaker-containers ERROR    Reporting training FAILURE\u001b[0m\n",
      "\u001b[34m2020-02-06 22:25:13,552 sagemaker-containers ERROR    framework error: \u001b[0m\n",
      "\u001b[34mTraceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/sagemaker_containers/_trainer.py\", line 81, in train\n",
      "    entrypoint()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/sagemaker_tensorflow_container/training.py\", line 211, in main\n",
      "    train(env, framework.mapping.to_cmd_args(user_hyperparameters))\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/sagemaker_tensorflow_container/training.py\", line 158, in train\n",
      "    runner=runner_type)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/sagemaker_containers/entry_point.py\", line 93, in run\n",
      "    install(user_entry_point, _env.code_dir, capture_error)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/sagemaker_containers/entry_point.py\", line 118, in install\n",
      "    entrypoint_type = _entry_point_type.get(dst, name)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/sagemaker_containers/_entry_point_type.py\", line 42, in get\n",
      "    elif name.endswith(\".py\"):\u001b[0m\n",
      "\u001b[34mAttributeError: 'NoneType' object has no attribute 'endswith'\n",
      "\u001b[0m\n",
      "\u001b[34m'NoneType' object has no attribute 'endswith'\u001b[0m\n",
      "\u001b[34mTraceback (most recent call last):\n",
      "  File \"/usr/local/bin/dockerd-entrypoint.py\", line 24, in <module>\n",
      "    subprocess.check_call(shlex.split(' '.join(sys.argv[1:])))\n",
      "  File \"/usr/lib/python3.6/subprocess.py\", line 311, in check_call\n",
      "    raise CalledProcessError(retcode, cmd)\u001b[0m\n",
      "\u001b[34msubprocess.CalledProcessError: Command '['train']' returned non-zero exit status 1.\u001b[0m\n"
     ]
    },
    {
     "ename": "UnexpectedStatusException",
     "evalue": "Error for Training job image-classifier-2020-02-06-22-22-22-554: Failed. Reason: AlgorithmError: framework error: \nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.6/dist-packages/sagemaker_containers/_trainer.py\", line 81, in train\n    entrypoint()\n  File \"/usr/local/lib/python3.6/dist-packages/sagemaker_tensorflow_container/training.py\", line 211, in main\n    train(env, framework.mapping.to_cmd_args(user_hyperparameters))\n  File \"/usr/local/lib/python3.6/dist-packages/sagemaker_tensorflow_container/training.py\", line 158, in train\n    runner=runner_type)\n  File \"/usr/local/lib/python3.6/dist-packages/sagemaker_containers/entry_point.py\", line 93, in run\n    install(user_entry_point, _env.code_dir, capture_error)\n  File \"/usr/local/lib/python3.6/dist-packages/sagemaker_containers/entry_point.py\", line 118, in install\n    entrypoint_type = _entry_point_type.get(dst, name)\n  File \"/usr/local/lib/python3.6/dist-packages/sagemaker_containers/_entry_point_type.py\", line 42, in get\n    elif name.endswith(\".py\"):\nAttributeError: 'NoneType' object has no attribute 'endswith'\n\n'N",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mUnexpectedStatusException\u001b[0m                 Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-12-9d75248fd8d6>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m     23\u001b[0m \u001b[0;31m#                              distributions={'parameter_server': {'enabled': True}})\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     24\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 25\u001b[0;31m \u001b[0mestimator\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfit\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mdata_location\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/estimator.py\u001b[0m in \u001b[0;36mfit\u001b[0;34m(self, inputs, wait, logs, job_name, experiment_config)\u001b[0m\n\u001b[1;32m    462\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mjobs\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mappend\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mlatest_training_job\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    463\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mwait\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 464\u001b[0;31m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mlatest_training_job\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwait\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mlogs\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mlogs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    465\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    466\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0m_compilation_job_name\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/estimator.py\u001b[0m in \u001b[0;36mwait\u001b[0;34m(self, logs)\u001b[0m\n\u001b[1;32m   1060\u001b[0m         \u001b[0;31m# If logs are requested, call logs_for_jobs.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1061\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mlogs\u001b[0m \u001b[0;34m!=\u001b[0m \u001b[0;34m\"None\"\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1062\u001b[0;31m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msagemaker_session\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mlogs_for_job\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mjob_name\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mwait\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mTrue\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mlog_type\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mlogs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1063\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1064\u001b[0m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msagemaker_session\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwait_for_job\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mjob_name\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/session.py\u001b[0m in \u001b[0;36mlogs_for_job\u001b[0;34m(self, job_name, wait, poll, log_type)\u001b[0m\n\u001b[1;32m   3001\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   3002\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mwait\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 3003\u001b[0;31m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_check_job_status\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mjob_name\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mdescription\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m\"TrainingJobStatus\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   3004\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mdot\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   3005\u001b[0m                 \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/session.py\u001b[0m in \u001b[0;36m_check_job_status\u001b[0;34m(self, job, desc, status_key_name)\u001b[0m\n\u001b[1;32m   2595\u001b[0m                 ),\n\u001b[1;32m   2596\u001b[0m                 \u001b[0mallowed_statuses\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m\"Completed\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m\"Stopped\"\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 2597\u001b[0;31m                 \u001b[0mactual_status\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mstatus\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   2598\u001b[0m             )\n\u001b[1;32m   2599\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mUnexpectedStatusException\u001b[0m: Error for Training job image-classifier-2020-02-06-22-22-22-554: Failed. Reason: AlgorithmError: framework error: \nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.6/dist-packages/sagemaker_containers/_trainer.py\", line 81, in train\n    entrypoint()\n  File \"/usr/local/lib/python3.6/dist-packages/sagemaker_tensorflow_container/training.py\", line 211, in main\n    train(env, framework.mapping.to_cmd_args(user_hyperparameters))\n  File \"/usr/local/lib/python3.6/dist-packages/sagemaker_tensorflow_container/training.py\", line 158, in train\n    runner=runner_type)\n  File \"/usr/local/lib/python3.6/dist-packages/sagemaker_containers/entry_point.py\", line 93, in run\n    install(user_entry_point, _env.code_dir, capture_error)\n  File \"/usr/local/lib/python3.6/dist-packages/sagemaker_containers/entry_point.py\", line 118, in install\n    entrypoint_type = _entry_point_type.get(dst, name)\n  File \"/usr/local/lib/python3.6/dist-packages/sagemaker_containers/_entry_point_type.py\", line 42, in get\n    elif name.endswith(\".py\"):\nAttributeError: 'NoneType' object has no attribute 'endswith'\n\n'N"
     ]
    }
   ],
   "source": [
    "account = sess.boto_session.client('sts').get_caller_identity()['Account']\n",
    "region = sess.boto_session.region_name\n",
    "image = '{}.dkr.ecr.{}.amazonaws.com/image-classifier:latest'.format(account, region)\n",
    "\n",
    "from sagemaker.tensorflow import TensorFlow\n",
    "\n",
    "estimator = sage.estimator.Estimator(image,\n",
    "                       role=role, \n",
    "                       train_instance_count=1, \n",
    "                       train_instance_type='local',\n",
    "                       #train_instance_type='ml.c5.2xlarge',\n",
    "                       output_path=\"s3://{}/output\".format(sess.default_bucket()),                       \n",
    "                       sagemaker_session=sess)\n",
    "\n",
    "# estimator = TensorFlow(image=image,\n",
    "#                              role=role,\n",
    "#                              train_instance_count=1,\n",
    "#                              train_instance_type='local',\n",
    "#                              #train_instance_type='ml.m5.4xlarge',\n",
    "#                              output_path=\"s3://{}/output\".format(sess.default_bucket()),\n",
    "#                              framework_version='2.0.0',\n",
    "#                              py_version='py3',\n",
    "#                              sagemaker_session=sess,\n",
    "#                              distributions={'parameter_server': {'enabled': True}})\n",
    "\n",
    "estimator.fit(data_location)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "conda_tensorflow_p36",
   "language": "python",
   "name": "conda_tensorflow_p36"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
